spring.application.name = escolaxyz

# Postgres com JPA
spring.jpa.database = PostgreSQL
spring.sql.init.platform = Postgres
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update

# Conexão
spring.datasource.url = jdbc:postgresql://localhost:5432/db_escola_xyz
spring.datasource.username = postgres
spring.datasource.password = postgres